### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by SteanlyCZ** [marteinn/wagtail-color-panel#11]
Hello,

if I set debug=True everything works as it should

but if I set debug=False, the server displays an error: Internal server error

Django==4.1.6
wagtail==4.2
wagtail-color-panel==1.4.0

where is the problem?

**Comment by marteinn** [comment]
Hi @SteanlyCZ and tanks for the bug report, could you provide more details so I can reproduce the issue?

For instance how you are using wagtail-color-panel (field (which field) or streamfield), where are you seeing the error (admin or template)?

**Comment by marteinn** [comment]
I'm closing this issue as I have not received any more information. Happy to open if provided more information.
