### ISSUE TITLE
Wagtail 5.1 Support?

### ISSUE THREAD

**Issue by tay-solis** [marteinn/wagtail-color-panel#13]
Hello!

I was wondering what the release timeline for Wagtail 5.1 support is. I see that there's a pull request that allows for 5.0 support. Do we have a deploy date for this update?

**Comment by marteinn** [comment]
Hi @tay-solis, apologies for the late reply, will look into adding Wagtail 5.2 support this weekend. To be continued.

**Comment by marteinn** [comment]
v1.5.0 now Includes Wagtail 5+ support: https://github.com/marteinn/wagtail-color-panel/releases/tag/v1.5.0
