### ISSUE TITLE
Updates for Wagtail 2.13

### ISSUE THREAD

**Issue by jacobcolyvan** [marteinn/wagtail-color-panel#2]
**_Context:_** With Wagtail's most recent upgrade to 2.13, it has caused issues with many custom blocks and Widget implementations due to a change in the client-side render rendering library (it now uses a lib called _telepath_). See here: https://docs.wagtail.io/en/stable/releases/2.13.html#new-client-side-implementation-for-custom-streamfield-blocks.

**_Problem_**: Since_ upgrading to Wagtail 2.13, the `NativeColorBlock` is having issues on initial render. Specifically the text input is rendering with the existing hex value, whilst the colour picker loads with the default #000000 value, and logs this error message: `The specified value "None" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers`. When you change the value in either input, they update each other as you'd expect, so it looks like it is specific to the initial page render. See below for screenshot for behaviour of block on page load:

![Screen Shot 2021-07-22 at 14 38 53](https://user-images.githubusercontent.com/60350555/126590643-4336e0de-124e-4463-9abc-8cebdcaf510a.png)

I've tried a few work arounds that fix the bug, but they're not very clean. One is just changing the name of the colour input component in `color-input-widget.html` from `"{{ widget_id }}-color"` to `"{{ widget.name}}"` (relevant file/line linked [here](https://github.com/marteinn/wagtail-color-panel/blob/develop/wagtail_color_panel/templates/wagtail_color_panel/widgets/color-input-widget.html#L5)). This seems to solve the issue, and everything works as we'd expect, but then we have two inputs with the same name, which may not be best practice.

@marteinn, I'm posting this ticket to see if you have a better solution than the above.

**Comment by webquest-nz** [comment]
I'm getting the same issue.

**Comment by marts** [comment]
@jacobcolyvan I had an issue with the widget rendering after a recent Wagtail upgrade, I've opened a PR that updates the widget to the _telepath_ way of doing things. Maybe you could have a look and see if it solves your problem. https://github.com/marteinn/wagtail-color-panel/pull/4

**Comment by marteinn** [comment]
Hi! Thanks to the fine work of @marts this issue should now be resolved in v1.3.0 (https://github.com/marteinn/wagtail-color-panel/releases/tag/v1.3.0)
