### ISSUE TITLE
Default value for NativeColorBlock

### ISSUE THREAD

**Issue by Eng-Ahmad-Almohammad** [marteinn/wagtail-color-panel#7]
The default value for NativeColorBlock is not working for me and when I checked the source code I could not find it the default option, but in the documentation example you were using the default option.

**Comment by marteinn** [comment]
Hi @Eng-Ahmad-Almohammad, I just tested using `NativeColorBlock` with a custom default color and it worked (using Wagtail 3/Python 3.9/Django 4.0.4. 

```python
# ...
from wagtail_color_panel.blocks import NativeColorBlock

class ArticlePage(HeadlessPreviewMixin, BasePage):
    content = StreamField([
        ('color', NativeColorBlock(default="#FF0000")),
    ], null=True)

    content_panels = BasePage.content_panels + [
        FieldPanel("content"),
    ]
```

Could you provide more details on how you are using NativeColorBlock?
Also please include your Wagtail, Django and Python version.
Thanks!

**Comment by marteinn** [comment]
Hi @Eng-Ahmad-Almohammad, just wanted to follow up on this, are you still having issues? Thanks!

**Comment by marteinn** [comment]
I'm closing this since as I'm missing feedback.
