### ISSUE TITLE
Support for Wagtail 3.0

### ISSUE THREAD

**Issue by johnunar** [marteinn/wagtail-color-panel#8]
When I use the NativeColorPanel with snippets, the color panel does not show up in cms.

EDIT: Maybe it is not a snippet-related problem after all, but a **Wagtail 3.0**-related problem.

```
@register_snippet
class MySnippet(models.Model):
    color = ColorField(default="#FFFFFF")

    panels = [
        NativeColorPanel("color"),
    ]
```

Is it possible to add support for snippets? 
Thank you!

**Comment by marteinn** [comment]
Hi @[johnunar](https://github.com/johnunar) and thanks for raising this issue. We just released [1.4.0 ](https://github.com/marteinn/wagtail-color-panel/releases/tag/v1.4.0) which should resolve the issue with panel not showing up on pages/snippets.
